/* data.js — ame-soeur-specific data */
window.APP_DATA = {
  maleNames: [
    "Louis", "Lucas", "Hugo", "Nathan", "Raphaël", "Arthur", "Jules", "Théo",
    "Gabriel", "Adam", "Tom", "Noah", "Maxime", "Ethan", "Mathis", "Axel",
    "Victor", "Alexandre", "Baptiste", "Romain", "Antoine", "Julien", "Nicolas",
    "Adrien", "Bastien", "Liam", "Aaron", "Rayan", "Léo", "Sacha", "Mohamed",
    "Nolan", "Robin", "Simon", "Clément", "Emile", "Oscar", "Matteo", "Enzo",
    "Valentin", "Dylan", "Thibault", "Arnaud", "Florian", "Quentin", "Gauthier",
    "Wout", "Senne", "Jarne", "Robbe", "Bram", "Tibo", "Jasper", "Ruben",
    "Dries", "Stef", "Pieter", "Mathijs", "Lars", "Jens", "Milan", "Niels",
    "Thomas", "Maxim", "Luca", "Yannick", "Loïc", "Kevin", "Sébastien",
    "Tanguy", "Corentin", "Aurélien", "Rémi", "Damien", "François", "Hadrien",
    "Tristan", "Timo", "Cédric", "Guillaume", "Laurent", "Benoît", "Olivier",
    "Xavier", "Charles", "Edouard", "Gilles", "Thierry", "Pierre", "Martin",
    "Elias", "Finn", "Milo", "Amir", "Ilias", "Ayoub", "Younes", "Zakaria",
    "Noé", "Augustin",
  ],

  femaleNames: [
    "Emma", "Jade", "Louise", "Léa", "Chloé", "Alice", "Manon", "Camille",
    "Inès", "Sarah", "Léna", "Clara", "Charlotte", "Zoé", "Juliette", "Eva",
    "Lina", "Anna", "Marie", "Margot", "Pauline", "Laura", "Romane", "Célia",
    "Elise", "Mia", "Olivia", "Nora", "Agathe", "Rose", "Gabrielle", "Ambre",
    "Victoire", "Adèle", "Anaïs", "Lucie", "Mathilde", "Clémence", "Margaux",
    "Eléonore", "Yasmine", "Fatima", "Nour", "Amira", "Sofia", "Elena", "Roos",
    "Lotte", "Fien", "Femke", "Jolien", "Silke", "Lien", "Noor", "Hanne",
    "Jana", "Eline", "Lies", "Katrien", "An", "Britt", "Fleur", "Axelle",
    "Marine", "Noémie", "Océane", "Valentine", "Constance", "Apolline",
    "Céleste", "Capucine", "Héloïse", "Aurore", "Maëlle", "Justine",
    "Caroline", "Amélie", "Audrey", "Estelle", "Emeline", "Morgane", "Solène",
    "Léonie", "Iris", "Lily", "Nina", "Mélissa", "Salomé", "Diane", "Alix",
    "Lou", "Lola", "Stella", "Chantal", "Brigitte", "Céline", "Delphine",
    "Elisa", "Fiona",
  ],
};
